version: '3.3'

services:
  lhservice:
    image: buildkite/puppeteer:latest
    volumes:
        - ./src:/app
        - ${GCP_KEY_PATH}:/tmp/keys/gcp-keyfile.json:ro
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:${PORT:-8080}"
    environment:
        PORT: ${PORT:-8080}
        K_SERVICE: lasso
        K_REVISION: 0
        K_CONFIGURATION: lasso
        BQ_DATASET: lh_results
        BQ_TABLE: lh_set
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/gcp-keyfile.json
        GOOGLE_CLOUD_PROJECT: 'lighthouse-service'
        CLOUD_TASKS_QUEUE: 'lhtests'
        CLOUD_TASKS_QUEUE_LOCATION: 'europe-west1'
        SERVICE_URL: ${SERVICE_URL}
